// <auto-generated />
using BurgerShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BurgerShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BurgerShop.Models.Burger", b =>
                {
                    b.Property<int>("BurgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBurgerOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BurgerId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Burgers");

                    b.HasData(
                        new
                        {
                            BurgerId = 1,
                            CategoryId = 1,
                            Description = "Our famous Chicken Burgers!",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/appleBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/appleBurger.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = true,
                            Name = "Chicken Burger",
                            Price = 350m
                        },
                        new
                        {
                            BurgerId = 2,
                            CategoryId = 2,
                            Description = "You'll love it!",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecake.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = false,
                            Name = "Cheese Burger",
                            Price = 850m
                        },
                        new
                        {
                            BurgerId = 3,
                            CategoryId = 2,
                            Description = "Plain cheese Burger. Plain pleasure.",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecake.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = false,
                            Name = "King Burger",
                            Price = 750m
                        },
                        new
                        {
                            BurgerId = 4,
                            CategoryId = 1,
                            Description = "A summer classic!",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherryBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherryBurger.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = false,
                            Name = "Junior Burger",
                            Price = 1500m
                        },
                        new
                        {
                            BurgerId = 5,
                            CategoryId = 3,
                            Description = "Happy holidays with this Burger!",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasappleBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasappleBurger.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = false,
                            Name = "Christmas Burger",
                            Price = 1390m
                        },
                        new
                        {
                            BurgerId = 6,
                            CategoryId = 3,
                            Description = "A Christmas favorite",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberryBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberryBurger.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = false,
                            Name = "Double Delight Burger",
                            Price = 1290m
                        },
                        new
                        {
                            BurgerId = 7,
                            CategoryId = 1,
                            Description = "Tasty as Beef",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachBurger.jpg",
                            InStock = false,
                            IsBurgerOfTheWeek = false,
                            Name = "Beef Burger",
                            Price = 1590m
                        },
                        new
                        {
                            BurgerId = 8,
                            CategoryId = 3,
                            Description = "Our Prawn favorite",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinBurger.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = true,
                            Name = "Prawn Burger",
                            Price = 1295m
                        },
                        new
                        {
                            BurgerId = 9,
                            CategoryId = 1,
                            Description = "My God, Sea Food!",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbBurger.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = true,
                            Name = "SeaFood Burger",
                            Price = 1195m
                        },
                        new
                        {
                            BurgerId = 10,
                            CategoryId = 1,
                            Description = "Our delicious Patty Burger!",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberryBurgersmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberryBurger.jpg",
                            InStock = true,
                            IsBurgerOfTheWeek = false,
                            Name = "Double Patty Burger",
                            Price = 595m
                        },
                        new
                        {
                            BurgerId = 11,
                            CategoryId = 2,
                            Description = "You'll love it!",
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg",
                            InStock = false,
                            IsBurgerOfTheWeek = false,
                            Name = "Tuna Cheese Burger",
                            Price = 1895m
                        });
                });

            modelBuilder.Entity("BurgerShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Chicken Burgers"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cheese Burgers"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Seasonal Burgers"
                        });
                });

            modelBuilder.Entity("BurgerShop.Models.Burger", b =>
                {
                    b.HasOne("BurgerShop.Models.Category", "Category")
                        .WithMany("Burgers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BurgerShop.Models.Category", b =>
                {
                    b.Navigation("Burgers");
                });
#pragma warning restore 612, 618
        }
    }
}
